version: '3'
services:
    nestjs-starter-kit:
        build:
            context: .
            dockerfile: ./Dockerfile
        image: nestjs-starter-kit
        ports:
            - '80:3000'
        container_name: nestjs-starter-kit
        volumes:
            - /app/node_modules
